// Manufacturer specifications; historical Letter geometry is retained verbatim.
export const onlineLabelsTemplates = [
  {
    id: 'onlinelabels-ol100',
    name: 'OnlineLabels OL100',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol100',
    widthIn: 4,
    heightIn: 1.32,
    nominalWidthIn: 4,
    nominalHeightIn: 1.33,
    columns: 2,
    rows: 7,
    marginTopIn: 0.88,
    marginBottomIn: 0.88,
    marginLeftIn: 0.1525,
    marginRightIn: 0.1525,
    columnGapIn: 0.195,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL100',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'General-purpose rectangular labels for text and identification.',
  },
  {
    id: 'onlinelabels-ol125',
    name: 'OnlineLabels OL125',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol125',
    widthIn: 4,
    heightIn: 2,
    nominalWidthIn: 4,
    nominalHeightIn: 2,
    columns: 2,
    rows: 5,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.18,
    marginRightIn: 0.18,
    columnGapIn: 0.14,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL125',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'General-purpose rectangular labels for text and identification.',
  },
  {
    id: 'onlinelabels-ol150',
    name: 'OnlineLabels OL150',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol150',
    widthIn: 4,
    heightIn: 3.344,
    nominalWidthIn: 4,
    nominalHeightIn: 3.33,
    columns: 2,
    rows: 3,
    marginTopIn: 0.4808,
    marginBottomIn: 0.4808,
    marginLeftIn: 0.14815,
    marginRightIn: 0.14815,
    columnGapIn: 0.2037,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL150',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'General-purpose rectangular labels for text and identification.',
  },
  {
    id: 'onlinelabels-ol250',
    name: 'OnlineLabels OL250',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol250',
    widthIn: 4,
    heightIn: 1.495,
    nominalWidthIn: 4,
    nominalHeightIn: 1.5,
    columns: 2,
    rows: 6,
    marginTopIn: 1.015,
    marginBottomIn: 1.015,
    marginLeftIn: 0.1725,
    marginRightIn: 0.1725,
    columnGapIn: 0.155,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL250',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'Wide labels for addresses and short identification text.',
  },
  {
    id: 'onlinelabels-ol400',
    name: 'OnlineLabels OL400',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol400',
    widthIn: 8.5,
    heightIn: 5.5,
    nominalWidthIn: 8.5,
    nominalHeightIn: 5.5,
    columns: 1,
    rows: 2,
    marginTopIn: 0,
    marginBottomIn: 0,
    marginLeftIn: 0,
    marginRightIn: 0,
    columnGapIn: 0,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL400',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'General-purpose rectangular labels for text and identification.',
  },
  {
    id: 'onlinelabels-ol450',
    name: 'OnlineLabels OL450',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol450',
    widthIn: 4.25,
    heightIn: 5.5,
    nominalWidthIn: 4.25,
    nominalHeightIn: 5.5,
    columns: 2,
    rows: 2,
    marginTopIn: 0,
    marginBottomIn: 0,
    marginLeftIn: 0,
    marginRightIn: 0,
    columnGapIn: 0,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL450',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'Quarter-sheet labels for parcels and storage.',
  },
  {
    id: 'onlinelabels-ol500',
    name: 'OnlineLabels OL500',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol500',
    widthIn: 4,
    heightIn: 3,
    nominalWidthIn: 4,
    nominalHeightIn: 3,
    columns: 2,
    rows: 3,
    marginTopIn: 1,
    marginBottomIn: 1,
    marginLeftIn: 0.1875,
    marginRightIn: 0.1875,
    columnGapIn: 0.125,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL500',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'General-purpose rectangular labels for text and identification.',
  },
  {
    id: 'onlinelabels-ol525',
    name: 'OnlineLabels OL525',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol525',
    widthIn: 4,
    heightIn: 3.25,
    nominalWidthIn: 4,
    nominalHeightIn: 3.25,
    columns: 2,
    rows: 3,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.156,
    marginRightIn: 0.156,
    columnGapIn: 0.1875,
    rowGapIn: 0.125,
    provider: 'OnlineLabels',
    code: 'OL525',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'General-purpose rectangular labels for text and identification.',
  },
  {
    id: 'onlinelabels-ol600',
    name: 'OnlineLabels OL600',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol600',
    widthIn: 4,
    heightIn: 2.5,
    nominalWidthIn: 4,
    nominalHeightIn: 2.5,
    columns: 2,
    rows: 4,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.18,
    marginRightIn: 0.18,
    columnGapIn: 0.14,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL600',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'Large labels for name tags and shipping details.',
  },
  {
    id: 'onlinelabels-ol700',
    name: 'OnlineLabels OL700',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol700',
    widthIn: 4,
    heightIn: 1.75,
    nominalWidthIn: 4,
    nominalHeightIn: 1.75,
    columns: 2,
    rows: 6,
    marginTopIn: 0.25,
    marginBottomIn: 0.25,
    marginLeftIn: 0.25,
    marginRightIn: 0.25,
    columnGapIn: 0,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL700',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'Wide labels for addresses and identification.',
  },
  {
    id: 'onlinelabels-ol750',
    name: 'OnlineLabels OL750',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol750',
    widthIn: 2.8333333,
    heightIn: 2.2,
    nominalWidthIn: 2.83,
    nominalHeightIn: 2.2,
    columns: 3,
    rows: 5,
    marginTopIn: 0,
    marginBottomIn: 0,
    marginLeftIn: 0,
    marginRightIn: 0,
    columnGapIn: 0,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL750',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'General-purpose rectangular labels for text and identification.',
  },
  {
    id: 'onlinelabels-ol800',
    name: 'OnlineLabels OL800',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol800',
    widthIn: 2.5,
    heightIn: 1.5625,
    nominalWidthIn: 2.5,
    nominalHeightIn: 1.563,
    columns: 3,
    rows: 6,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.375,
    marginRightIn: 0.375,
    columnGapIn: 0.125,
    rowGapIn: 0.125,
    provider: 'OnlineLabels',
    code: 'OL800',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'Compact labels for names and product identification.',
  },
  {
    id: 'onlinelabels-ol875',
    name: 'OnlineLabels OL875',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol875',
    widthIn: 2.5935,
    heightIn: 1,
    nominalWidthIn: 2.625,
    nominalHeightIn: 1,
    columns: 3,
    rows: 10,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.21975,
    marginRightIn: 0.21975,
    columnGapIn: 0.14,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL875',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'General-purpose rectangular labels for text and identification.',
  },
  {
    id: 'onlinelabels-ol900',
    name: 'OnlineLabels OL900',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol900',
    widthIn: 2.833,
    heightIn: 1,
    nominalWidthIn: 2.83,
    nominalHeightIn: 1,
    columns: 3,
    rows: 11,
    marginTopIn: 0,
    marginBottomIn: 0,
    marginLeftIn: 0,
    marginRightIn: 0,
    columnGapIn: 0,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL900',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'General-purpose rectangular labels for text and identification.',
  },
  {
    id: 'onlinelabels-ol1000',
    name: 'OnlineLabels OL1000',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol1000',
    widthIn: 1.5,
    heightIn: 1,
    nominalWidthIn: 1.5,
    nominalHeightIn: 1,
    columns: 5,
    rows: 10,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.25,
    marginRightIn: 0.25,
    columnGapIn: 0.125,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL1000',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'Small labels for short names and inventory codes.',
  },
  {
    id: 'onlinelabels-ol1100',
    name: 'OnlineLabels OL1100',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol1100',
    widthIn: 1.5,
    heightIn: 0.5,
    nominalWidthIn: 1.5,
    nominalHeightIn: 0.5,
    columns: 5,
    rows: 20,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.5,
    marginRightIn: 0.5,
    columnGapIn: 0,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL1100',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'Narrow labels for short text and identification codes.',
  },
  {
    id: 'onlinelabels-ol175',
    name: 'OnlineLabels OL175',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol175',
    widthIn: 8.5,
    heightIn: 11,
    nominalWidthIn: 8.5,
    nominalHeightIn: 11,
    columns: 1,
    rows: 1,
    marginTopIn: 0,
    marginBottomIn: 0,
    marginLeftIn: 0,
    marginRightIn: 0,
    columnGapIn: 0,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL175',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'General-purpose rectangular labels for text and identification.',
  },
  {
    id: 'onlinelabels-ol200',
    name: 'OnlineLabels OL200',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol200',
    widthIn: 3.4375,
    heightIn: 0.6656,
    nominalWidthIn: 3.4375,
    nominalHeightIn: 0.669,
    columns: 2,
    rows: 15,
    marginTopIn: 0.508,
    marginBottomIn: 0.508,
    marginLeftIn: 0.53125,
    marginRightIn: 0.53125,
    columnGapIn: 0.5625,
    rowGapIn: 0,
    provider: 'OnlineLabels',
    code: 'OL200',
    paperSize: 'Letter',
    sheetWidthIn: 8.5,
    sheetHeightIn: 11,
    coverageDescription: 'Narrow labels for filing and short identification text.',
  },
  {
    id: 'onlinelabels-eu30142',
    name: 'OnlineLabels EU30142',
    provider: 'OnlineLabels',
    code: 'EU30142',
    paperSize: 'A4',
    sheetWidthIn: 8.267716535433072,
    sheetHeightIn: 11.692913385826772,
    widthIn: 3.1496062992125986,
    heightIn: 2.362204724409449,
    nominalWidthIn: 3.1496062992125986,
    nominalHeightIn: 2.362204724409449,
    columns: 2,
    rows: 4,
    marginTopIn: 0.8267716535433072,
    marginBottomIn: 0.8267716535433072,
    marginLeftIn: 0.8858267716535434,
    marginRightIn: 0.8858267716535434,
    columnGapIn: 0.1968503937007874,
    rowGapIn: 0.1968503937007874,
    coverageDescription: 'Medium labels for products and identification.',
    sourceUrl: 'https://uk.onlinelabels.com/templates/blank/eu30142',
  },
  {
    id: 'onlinelabels-eu30147',
    name: 'OnlineLabels EU30147',
    provider: 'OnlineLabels',
    code: 'EU30147',
    paperSize: 'A4',
    sheetWidthIn: 8.267716535433072,
    sheetHeightIn: 11.692913385826772,
    widthIn: 2.7559055118110236,
    heightIn: 1.968503937007874,
    nominalWidthIn: 2.7559055118110236,
    nominalHeightIn: 1.968503937007874,
    columns: 2,
    rows: 5,
    marginTopIn: 0.531496062992126,
    marginBottomIn: 0.531496062992126,
    marginLeftIn: 1.2795275590551183,
    marginRightIn: 1.2795275590551183,
    columnGapIn: 0.1968503937007874,
    rowGapIn: 0.1968503937007874,
    coverageDescription: 'Compact labels for names and identification.',
    sourceUrl: 'https://uk.onlinelabels.com/templates/blank/eu30147',
  },
] as const
