export type LabelTemplateId = (typeof labelTemplates)[number]['id']

export const defaultLabelTemplateId: LabelTemplateId = 'townstix-us-10'

export const labelTemplates = [
  {
    id: 'townstix-us-10',
    name: 'TownStix US-10',
    nominalWidthIn: 4,
    sourceUrl: 'https://townstix.com/templates/',
    widthIn: 4,
    heightIn: 2,
    nominalHeightIn: 2,
    columns: 2,
    rows: 5,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.25,
    marginRightIn: 0.25,
    columnGapIn: 0,
    rowGapIn: 0,
  },
  {
    id: 'avery-5390',
    name: 'Avery 5390',
    nominalWidthIn: 3.5,
    sourceUrl: 'https://www.avery.com/templates/5390',
    widthIn: 3.5,
    // Product dimensions are nominal; printing follows Avery's official PDF:
    // https://s3.amazonaws.com/avery.dpp.projects.s3uspdownloadables/CA_en/Downloadables/pdf/U-0119-01.pdf
    // Letter 612×792pt. Columns x=54,306,558; rows y=76.5 + n×159.75pt.
    heightIn: 159.75 / 72,
    nominalHeightIn: 2.25,
    columns: 2,
    rows: 4,
    marginTopIn: 76.5 / 72,
    marginBottomIn: 76.5 / 72,
    marginLeftIn: 0.75,
    marginRightIn: 0.75,
    columnGapIn: 0,
    rowGapIn: 0,
  },
  // Manufacturer detailed specifications, reviewed 2026-09-07. See docs/label-catalog-research.md.
  {
    id: 'onlinelabels-ol100',
    name: 'OnlineLabels OL100',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol100',
    widthIn: 4.0,
    heightIn: 1.32,
    nominalWidthIn: 4.0,
    nominalHeightIn: 1.33,
    columns: 2,
    rows: 7,
    marginTopIn: 0.88,
    marginBottomIn: 0.88,
    marginLeftIn: 0.1525,
    marginRightIn: 0.1525,
    columnGapIn: 0.195,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol125',
    name: 'OnlineLabels OL125',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol125',
    widthIn: 4.0,
    heightIn: 2.0,
    nominalWidthIn: 4.0,
    nominalHeightIn: 2.0,
    columns: 2,
    rows: 5,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.18,
    marginRightIn: 0.18,
    columnGapIn: 0.14,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol150',
    name: 'OnlineLabels OL150',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol150',
    widthIn: 4.0,
    heightIn: 3.344,
    nominalWidthIn: 4.0,
    nominalHeightIn: 3.33,
    columns: 2,
    rows: 3,
    marginTopIn: 0.4808,
    marginBottomIn: 0.4808,
    marginLeftIn: 0.14815,
    marginRightIn: 0.14815,
    columnGapIn: 0.2037,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol250',
    name: 'OnlineLabels OL250',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol250',
    widthIn: 4.0,
    heightIn: 1.495,
    nominalWidthIn: 4.0,
    nominalHeightIn: 1.5,
    columns: 2,
    rows: 6,
    marginTopIn: 1.015,
    marginBottomIn: 1.015,
    marginLeftIn: 0.1725,
    marginRightIn: 0.1725,
    columnGapIn: 0.155,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol400',
    name: 'OnlineLabels OL400',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol400',
    widthIn: 8.5,
    heightIn: 5.5,
    nominalWidthIn: 8.5,
    nominalHeightIn: 5.5,
    columns: 1,
    rows: 2,
    marginTopIn: 0.0,
    marginBottomIn: 0.0,
    marginLeftIn: 0.0,
    marginRightIn: 0.0,
    columnGapIn: 0.0,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol450',
    name: 'OnlineLabels OL450',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol450',
    widthIn: 4.25,
    heightIn: 5.5,
    nominalWidthIn: 4.25,
    nominalHeightIn: 5.5,
    columns: 2,
    rows: 2,
    marginTopIn: 0.0,
    marginBottomIn: 0.0,
    marginLeftIn: 0.0,
    marginRightIn: 0.0,
    columnGapIn: 0.0,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol500',
    name: 'OnlineLabels OL500',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol500',
    widthIn: 4.0,
    heightIn: 3.0,
    nominalWidthIn: 4.0,
    nominalHeightIn: 3.0,
    columns: 2,
    rows: 3,
    marginTopIn: 1.0,
    marginBottomIn: 1.0,
    marginLeftIn: 0.1875,
    marginRightIn: 0.1875,
    columnGapIn: 0.125,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol525',
    name: 'OnlineLabels OL525',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol525',
    widthIn: 4.0,
    heightIn: 3.25,
    nominalWidthIn: 4.0,
    nominalHeightIn: 3.25,
    columns: 2,
    rows: 3,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.156,
    marginRightIn: 0.156,
    columnGapIn: 0.1875,
    rowGapIn: 0.125,
  },
  {
    id: 'onlinelabels-ol600',
    name: 'OnlineLabels OL600',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol600',
    widthIn: 4.0,
    heightIn: 2.5,
    nominalWidthIn: 4.0,
    nominalHeightIn: 2.5,
    columns: 2,
    rows: 4,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.18,
    marginRightIn: 0.18,
    columnGapIn: 0.14,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol700',
    name: 'OnlineLabels OL700',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol700',
    widthIn: 4.0,
    heightIn: 1.75,
    nominalWidthIn: 4.0,
    nominalHeightIn: 1.75,
    columns: 2,
    rows: 6,
    marginTopIn: 0.25,
    marginBottomIn: 0.25,
    marginLeftIn: 0.25,
    marginRightIn: 0.25,
    columnGapIn: 0.0,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol750',
    name: 'OnlineLabels OL750',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol750',
    widthIn: 2.8333333,
    heightIn: 2.2,
    nominalWidthIn: 2.83,
    nominalHeightIn: 2.2,
    columns: 3,
    rows: 5,
    marginTopIn: 0.0,
    marginBottomIn: 0.0,
    marginLeftIn: 0.0,
    marginRightIn: 0.0,
    columnGapIn: 0.0,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol800',
    name: 'OnlineLabels OL800',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol800',
    widthIn: 2.5,
    heightIn: 1.5625,
    nominalWidthIn: 2.5,
    nominalHeightIn: 1.563,
    columns: 3,
    rows: 6,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.375,
    marginRightIn: 0.375,
    columnGapIn: 0.125,
    rowGapIn: 0.125,
  },
  {
    id: 'onlinelabels-ol875',
    name: 'OnlineLabels OL875',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol875',
    widthIn: 2.5935,
    heightIn: 1.0,
    nominalWidthIn: 2.625,
    nominalHeightIn: 1.0,
    columns: 3,
    rows: 10,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.21975,
    marginRightIn: 0.21975,
    columnGapIn: 0.14,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol900',
    name: 'OnlineLabels OL900',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol900',
    widthIn: 2.833,
    heightIn: 1.0,
    nominalWidthIn: 2.83,
    nominalHeightIn: 1.0,
    columns: 3,
    rows: 11,
    marginTopIn: 0.0,
    marginBottomIn: 0.0,
    marginLeftIn: 0.0,
    marginRightIn: 0.0,
    columnGapIn: 0.0,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol1000',
    name: 'OnlineLabels OL1000',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol1000',
    widthIn: 1.5,
    heightIn: 1.0,
    nominalWidthIn: 1.5,
    nominalHeightIn: 1.0,
    columns: 5,
    rows: 10,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.25,
    marginRightIn: 0.25,
    columnGapIn: 0.125,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol1100',
    name: 'OnlineLabels OL1100',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol1100',
    widthIn: 1.5,
    heightIn: 0.5,
    nominalWidthIn: 1.5,
    nominalHeightIn: 0.5,
    columns: 5,
    rows: 20,
    marginTopIn: 0.5,
    marginBottomIn: 0.5,
    marginLeftIn: 0.5,
    marginRightIn: 0.5,
    columnGapIn: 0.0,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol175',
    name: 'OnlineLabels OL175',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol175',
    widthIn: 8.5,
    heightIn: 11.0,
    nominalWidthIn: 8.5,
    nominalHeightIn: 11.0,
    columns: 1,
    rows: 1,
    marginTopIn: 0.0,
    marginBottomIn: 0.0,
    marginLeftIn: 0.0,
    marginRightIn: 0.0,
    columnGapIn: 0.0,
    rowGapIn: 0.0,
  },
  {
    id: 'onlinelabels-ol200',
    name: 'OnlineLabels OL200',
    sourceUrl: 'https://www.onlinelabels.com/templates/blank/ol200',
    widthIn: 3.4375,
    heightIn: 0.6656,
    nominalWidthIn: 3.4375,
    nominalHeightIn: 0.669,
    columns: 2,
    rows: 15,
    marginTopIn: 0.508,
    marginBottomIn: 0.508,
    marginLeftIn: 0.53125,
    marginRightIn: 0.53125,
    columnGapIn: 0.5625,
    rowGapIn: 0,
  },
] as const

export function getLabelTemplate(id: unknown = defaultLabelTemplateId) {
  const template = labelTemplates.find(template => template.id === id)
  if (!template) throw new RangeError('Unknown label template')
  return template
}
